'use client';

import './globals.css';

import { useState } from 'react';
import { ColorModeContext, useMode } from '@/theme';
import { CssBaseline, ThemeProvider } from '@mui/material';
import Topbar from '@/scenes/global/Topbar';
import Sidebar from '@/scenes/global/Sidebar';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
  const [theme, colorMode] = useMode();
  const [isSidebar, setIsSidebar] = useState(true);

  return (
    <html lang='en'>
      <body suppressHydrationWarning={true}>
        <ColorModeContext.Provider value={colorMode}>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <div className='app'>
              <Sidebar isSidebar={setIsSidebar} />
              <main className='content'>
                <Topbar setIsSidebar={setIsSidebar} />
                {children}
              </main>
            </div>
          </ThemeProvider>
        </ColorModeContext.Provider>
      </body>
    </html>
  );
}
