'use client';

import { Inter } from 'next/font/google';
import './globals.css';

import { ColorModeContext, useMode } from '@/theme';
import { CssBaseline, ThemeProvider } from '@mui/material';
import Topbar from '@/scenes/global/Topbar';
import Dashboard from '@/scenes/dashboard/page';
import Sidebar from '@/scenes/global/Sidebar';
// import Team from '@/scenes/team/page';
// import Invoices from '@/scenes/invoices/page';
// import Contants from '@/scenes/contants/page';
// import Bar from '@/scenes/bar/page';
// import Form from '@/scenes/form/page';
// import Line from '@/scenes/line/page';
// import Pie from '@/scenes/pie/page';
// import FAQ from '@/scenes/faq/page';
// import Geography from '@/scenes/geography/page';
// import Calendar from '@/scenes/calendar/page';

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
  const [theme, colorMode] = useMode();

  return (
    <html lang='en'>
      <body className={inter.className}>
        <ColorModeContext.Provider value={colorMode}>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <div>
              {/* <Sidebar /> */}
              <main className='content'>
                <Topbar />
                <Dashboard />
                {children}
              </main>
            </div>
          </ThemeProvider>
        </ColorModeContext.Provider>
      </body>
    </html>
  );
}
